"""Review flag constants."""

# Mandatory field flags
TENANT_NAME_MISSING = "TENANT_NAME_MISSING"
LANDLORD_NAME_MISSING = "LANDLORD_NAME_MISSING"
PREMISES_ADDRESS_MISSING = "PREMISES_ADDRESS_MISSING"
COMMENCEMENT_DATE_MISSING = "COMMENCEMENT_DATE_MISSING"
EXPIRY_DATE_MISSING = "EXPIRY_DATE_MISSING"
MONTHLY_RENT_MISSING = "MONTHLY_RENT_MISSING"

# Area
AREA_NOT_FOUND = "AREA_NOT_FOUND"

# Dates
TERM_COMPUTED_NOT_EXPLICIT = "TERM_COMPUTED_NOT_EXPLICIT"
MULTIPLE_SIGNING_DATES = "MULTIPLE_SIGNING_DATES"
DATE_ORDER_INVALID = "DATE_ORDER_INVALID"
TERM_MONTHS_MISMATCH = "TERM_MONTHS_MISMATCH"

# Financials
DEPOSIT_COMPOSITION_NEEDS_CHECK = "DEPOSIT_COMPOSITION_NEEDS_CHECK"
RATES_CONVERTED_QUARTERLY_TO_MONTHLY = "RATES_CONVERTED_QUARTERLY_TO_MONTHLY"

# Clauses
CLAUSE_SUMMARY_LOW_CONFIDENCE = "CLAUSE_SUMMARY_LOW_CONFIDENCE"
PARKING_UNCLEAR = "PARKING_UNCLEAR"
RESTORATION_UNCLEAR = "RESTORATION_UNCLEAR"
RENEWAL_UNCLEAR = "RENEWAL_UNCLEAR"
SIGNAGE_UNCLEAR = "SIGNAGE_UNCLEAR"
SUBLETTING_UNCLEAR = "SUBLETTING_UNCLEAR"

# Break / termination
BREAK_INCONSISTENCY = "BREAK_INCONSISTENCY"

# Other
OCR_USED = "OCR_USED"
FIT_OUT_MAPPED_FROM_RENT_FREE = "FIT_OUT_MAPPED_FROM_RENT_FREE"
